version: "3.9"

services:
  mongo:
    image: docker.arvancloud.ir/mongo:7               # official image
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  faiss-db:
    build: ./faiss-db
    container_name: faiss-db
    depends_on:
      - mongo
    environment:
      FAISS_INDEX_PATH: /app/data/index.faiss
      EMBEDDING_DIM: 1536
      SERVICE_PORT: 8080
    volumes:
      - faiss-data:/app/data
    ports:
      - "8080:8080"

  service-fetcher:
    build: ./service-fetcher
    container_name: service-fetcher
    depends_on:
      - mongo
      - faiss-db
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017
      FAISS_ENDPOINT: http://faiss-db:8080
      SERVICE_PORT: 8000
    ports:
      - "8000:8000"

volumes:
  mongo-data:
  faiss-data:
